# Generated by Django 3.0.5 on 2021-11-23 08:43

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', mirage.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('text', mirage.fields.EncryptedTextField(blank=True, null=True)),
                ('integer', mirage.fields.EncryptedIntegerField(blank=True, max_length=64, null=True)),
                ('email', mirage.fields.EncryptedEmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
