# Generated by Django 4.0 on 2021-12-25 03:30

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_testmodel_textraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='url',
            field=mirage.fields.EncryptedURLField(blank=True, null=True),
        ),
    ]
