# Generated by Django 4.0 on 2022-03-14 02:41

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_testmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='json',
            field=mirage.fields.EncryptedJSONField(default={}),
        ),
    ]
